### ISSUE TITLE
Integrar proyecto con Heroku

### ISSUE THREAD

**Issue by javviram** [EGC-DECIDE-IO-Visualizacion/decide-io#11]
**¿Está tu petición de mejora relacionada con un problema? Por favor, describelo**
Se desea integrar el proyecto con Heroku para conseguir la automatización del despliegue.

**Describe la solución que te gustaría que se implementase**
Se debería integrar Heroku con Github, de tal modo que, una vez pasado las pruebas de Travis, se cree un nuevo artefacto y se despliegue en el servidor. Este despliegue se debería realizar de forma automática, sin que el miembro que realiza en commit tenga que hacer nada más.

**Describe posibles alternativas que hayas considerado**
Una posible alternativa podría ser modificar el fichero de configuración de travis para que sea éste quien se encargue de comunicarse con Heroku y realizar el despliegue una vez terminado las pruebas.

**Comment by javviram** [comment]
Se ha creado un correo outlook y una cuenta en heroku para el despliegue. Si se necesitan los credenciales, ponerse en contacto conmigo.

**Comment by javviram** [comment]
Se ha realizado la integración, pero tras insertar los credenciales, se produce una excepción.

**Comment by javviram** [comment]
Se ha realizado la integración con Heroku. 
Actualmente, cuando se realiza un commit en la rama master, automáticamente Travis realiza las pruebas oportunas, y si el código ha pasado todas las pruebas, de forma automática también, Heroku realiza un nuevo despliegue.

El único proceso manual que se realiza es la creación inicial de credenciales para el administrador, tarea que solo se realiza una vez. Para crear un nuevo usuario, desde el terminal escribimos el siguiente comando:
`heroku run -a decideiovisualizer "sh -c 'cd decide && python manage.py createsuperuser'"`

**Comment by javviram** [comment]
Se asigna a @CarlosGuerraLora la tarea de comprobar que realmente se puede acceder a la web y todo funciona correctamente.

**Comment by CarlosGuerraLora** [comment]
Se ha comprobado que todo funciona correctamente y que no hay ningún fallo
