### ISSUE TITLE
Visualización de datos adicionales sobre una votación

### ISSUE THREAD

**Issue by walviealv** [EGC-DECIDE-IO-Visualizacion/decide-io#3]
**¿Está tu petición de mejora relacionada con un problema? Por favor, describelo**
No

**Describe la solución que te gustaría que se implementase**
Una vista para mostrar datos estadísticos referentes a una votación. Podría llegar a ser la propia vista principal de visualización de voto. 

**Describe posibles alternativas que hayas considerado**
Implementar una nueva vista o reutilizar la vista principal, eso sí, debe estar presente durante todo el tiempo de votación y no solo después de cerrar la votación y el recuento. 

**Contenido adicional**
Los datos a mostrar se obtendrán desde el subsistema de almacenamiento en el siguiente formato:

```
GET: store/stats/<voting_id>
```

La llamada a esta API devolverá un JSON con los siguientes atributos: 
``` 
"numero_personas_censo": Total de personas en el censo.

"numero_personas_votado": Total de personas que han votado.

"porcentaje_participacion": Porcentaje de participación.

"rango_menor_20": Número de personas en el censo con menos de 20 años.

"rango_entre_20_40": Número de personas en el censo con entre 20 y 40 años.

"rango_entre_40_60": Número de personas en el censo con entre 40 y 60 años.

"rango_mayor_60": Número de personas en el censo con más de 60 años.

"edad_media": Edad media de los votantes del censo.

"porcentaje_rango_menor_20": Porcentaje de personas que han votado con menos de 20 años.

"porcentaje_rango_entre_20_40": Porcentaje de personas que han votado con entre 20 y 40 años.

"porcentaje_rango_entre_40_60": Porcentaje de personas que han votado con entre 40 y 60 años.

"porcentaje_rango_mayor_60": Porcentaje de personas que han votado con más de 60 años.

"numero_hombres": Número de hombres en el censo. 

"numero_mujeres": Número de mujeres en el censo.

"porcentaje_votos_hombres": Porcentaje de hombres que han votado.

"porcentaje_votos_mujeres": Porcentaje de mujeres que han votado.

"census_users_lugares_dict": {
           "lugar_1" : Número de personas de 'lugar_1' en el censo.
           "lugar_2" : Número de personas de 'lugar_2' en el censo. 
           ...
} (Diccionario de Python)

"porcentaje_votes_users_lugares_dict":  {
           "lugar_1" : Porcentaje de personas que han votado de 'lugar_1'.
           "lugar_2" : Porcentaje de personas que han votado de 'lugar_2'.
           ...
} (Diccionario de Python)
```

La API está a la espera de que el equipo encargado del subsistema de autenticación integre en el repositorio principal los cambios necesarios correspondientes. Se notificará en el momento que esté operativa.

**Comment by AmadeusGraves** [comment]
DUDA @walviealv. La llamada a la API desde donde deberia realizarse.

¿Esta llamada debería realizarse desde views.py y pasar el contendido al html?
¿Se pueden extraer los datos del json?
¿La uri completa de la API como seria?

**Comment by walviealv** [comment]
**¿Esta llamada debería realizarse desde views.py y pasar el contendido al html?**
Si hacerlo en el views.py es una opción, haces la llamada desde el controlador y envías a la vista los datos necesarios que representar. También podrías dejar simplemente el controlador para mandarlo a la vista y que sea en el propio html, con javascript, la petición a la API y la representación de los datos. 

**¿Se pueden extraer los datos del json?**
Si, haces la petición a la API, y el JSON que te devuelve puedes leerlo haciendo uso de cualquier librería. Por ejemplo, con la librería estándar de python para json.  `import json`. (si lo hacéis la petición por views.py). 

**¿La uri completa de la API como seria?**
GET: store/stats/<voting_id>
Por ejemplo, en un entorno de desarrollo sería: http://localhost:8000/store/stats/491

**UPDATE**
Si te puede servir de ayuda, te adjunto el fichero de test que se utilizado para probar la API. A partir de la línea 258 puedes ver como obtener el JSON y los valores de los diferentes atributos. (https://github.com/DecideIO-Almacenamiento/decide-io-almacenamiento/blob/0d5651c3600257b073bd72af507acc48e7d20595/decide/store/tests.py).

**Comment by AmadeusGraves** [comment]
DUDA. @walviealv. Esta llamada ya le tenéis implementada y subida a GitHub? Estoy haciendo algunas pruebas pero necesito hacer la llamada real para comprobar que obtengo los datos y los puedo procesar correctamente. Si ya lo tenéis hecho podemos crear una rama en común.

**Comment by AmadeusGraves** [comment]
El desarrollo ha terminado aunque el metodo de la llamada API es un ejemplo ya que se requiere la integracion entre los 2 equipos, Store y Visualizer para poder realizar la llamada correctamente.

**Comment by walviealv** [comment]
Los cambios por parte de Store están subidos en nuestro [master](https://github.com/DecideIO-Almacenamiento/decide-io-almacenamiento). Si queréis podéis hacernos un pull request con vuestra parte, o clonar nuestro repositorio para hacer vuestras pruebas. 

Seguramente tendréis que crear usuarios por código (podéis usar el test, como ejemplo) o a través del admin, ya que por parte del equipo de Autenticación no se ha finalizado aún el desarrollo de los registros incluyendo los nuevos parámetros.

**Comment by AmadeusGraves** [comment]
Se ha llevado a cabo la integración con la rama master, se han añadido las mejoras a esta, se procede a cerrar la issue.

**Comment by AmadeusGraves** [comment]
> Los cambios por parte de Store están subidos en nuestro [master](https://github.com/DecideIO-Almacenamiento/decide-io-almacenamiento). Si queréis podéis hacernos un pull request con vuestra parte, o clonar nuestro repositorio para hacer vuestras pruebas.
> 
> Seguramente tendréis que crear usuarios por código (podéis usar el test, como ejemplo) o a través del admin, ya que por parte del equipo de Autenticación no se ha finalizado aún el desarrollo de los registros incluyendo los nuevos parámetros.

@walviealv  No funciona, visualizer puede verlo cualquier usuario, incluso uno no logueado, ademas los usuarios pueden tener el profile vacio. Esta ultima parte da problemas. No puedo incorporar vuestro método hasta que este solucionado. Os envio una captura de pantalla.

![image](https://user-images.githubusercontent.com/18572939/51077199-60249000-16a3-11e9-9399-7c8d5f2001b7.png)

**Comment by AmadeusGraves** [comment]
@walviealv Una solucion podría ser que vuestro metodo no tuviera en cuenta los usuarios sin profile.

**Comment by walviealv** [comment]
**Visualizer puede verlo cualquier usuario, incluso uno no logueado** 
No es ningún problema, esta pensado así.

**Ademas los usuarios pueden tener el profile vacio**
Como os comenté, el modelo está pendiente del equipo de autenticación, actualmente funciona con un Stub que hemos hecho por nuestra parte, por eso cualquier usuario registrado anteriormente a nuestro modelo, o nuevo usuario registrado que no tenga esas propiedades va a fallar. Le recomiendo que cree los usuarios nuevos por el panel de admin o por código. Cuando el equipo de autenticación cree un modelo como el nuestro y incluya la correspondiente vista de registro con los nuevos datos, ese error no debería volver a ocurrir. Aún así, tiene sentido no tener en cuenta a usuarios sin profile, ya que en un sistema en explotación los cambios en el modelo no deberían afectar al funcionamiento de la aplicación. Nos ponemos con el cambio y les notifico en cuanto este solucionado. 

**UPDATE**
Recordad que un cambio en el modelo requiere que volváis a migrar la base de datos. Que no sabemos si lo habéis hecho. 

Un saludo.

**Comment by danieldml112** [comment]
Se ha corregido el comportamiento de la API para poder soportar usuarios sin profile o sin datos rellenados en el modelo profile. La versión corregida se puede encontrar en la rama master del repositorio de decide-io-almacenamiento. [Aquí un enlace para poder acceder a ella.](https://github.com/DecideIO-Almacenamiento/decide-io-almacenamiento/issues/1#issuecomment-453836172)

**Comment by AmadeusGraves** [comment]
Se procederá a integrar el vuestro código.

**Comment by AmadeusGraves** [comment]
Se ha integrado el código de Almacenamiento (Issue #17 ) y se ha usado la llamada API para obtener los datos. Se cierra la Issue.
