### ISSUE TITLE
Definir una nueva interfaz usable con CSS

### ISSUE THREAD

**Issue by javviram** [EGC-DECIDE-IO-Visualizacion/decide-io#4]
**¿Está tu petición de mejora relacionada con un problema? Por favor, describelo**
Se desea mejorar la interfaz actual de visualización mediante CSS. El objetivo de esta tarea es mostrar la información actual de una forma más amigable para el usuario.

Para realizar esta tarea se debe realizar 2 subtareas:
- Remodelar la vista actual con CSS.
- Definir pruebas para Travis CI.

**Describe la solución que te gustaría que se implementase**
Una interfaz con cabecera donde se mostrase la información de los resultados de las votaciones de forma estructurada y clara.

**Comment by javviram** [comment]
Se finaliza el desarrollo de la tarea. Debido a que el código añadido unicamente se corresponde con CSS y HTML, no se ha desarrollado ningún test adicional para Travis.
Falta realizar pruebas e integrar la rama con la master.

**Comment by JesusPerezCarmona** [comment]
Se ha comprobado que con mi base de datos funciona correctamente. Por lo tanto procedo al cierre de la incidencia.
