### ISSUE TITLE
Mostrar resultados en tiempo real

### ISSUE THREAD

**Issue by javviram** [EGC-DECIDE-IO-Visualizacion/decide-io#5]
**¿Está tu petición de mejora relacionada con un problema? Por favor, describelo**
Se desea añadir una nueva característica en el módulo de visualización mediante el cual sea posible ver los resultados de las encuestas en tiempo real.

**Describe la solución que te gustaría que se implementase**
Actualmente, solo es posible ver los resultados de una encuesta una vez terminada. Lo ideal sería poder ver dichos resultados en cualquier momento.

Esta tarea se puede dividir en las siguientes subtareas:
- Modificar visualizer
- Modificar Views
- Coordinarse con el equipo del módulo Voting para modificar la función Tally
- Crear pruebas para Travis CI

**Comment by AmadeusGraves** [comment]
A la espera de que el modulo de votación hagan avances en la creación del método "Tally" que haga el recuento de votos automáticamente sin tener que esperar al administrador que lo haga manualmente para que en el Visualizer se muestre siempre la tabla de resultados de la votación actualizados. Cuando el equipo de Votación, realice el método, adaptare mi código a su trabajo, de momento hay un método de ejemplo.

**Comment by AmadeusGraves** [comment]
Se ha llevado a cabo la integración con la rama master, se han añadido las mejoras a esta, se procede a cerrar la issue.
