### ISSUE TITLE
Pintado de gráficas y estudio de datos

### ISSUE THREAD

**Issue by javviram** [EGC-DECIDE-IO-Visualizacion/decide-io#6]
**¿Está tu petición de mejora relacionada con un problema? Por favor, describelo**
Se desea mostrar gráficas de los resultados de las encuestas.

**Describe la solución que te gustaría que se implementase**
Se debería mostrar gráficas donde se muestren las opciones votadas y los porcentajes.

**Describe posibles alternativas que hayas considerado**
El tipo de gráfica puede ser de muchos tipos: ciruclar, de barras, etc...

**Comment by CarlosGuerraLora** [comment]
En Visual Studio salen errores de sintaxis que, sin embargo, no son notorios a la hora de probar esta funcionalidad, ya que las gráficas salen sin problemas y con los datos exactos de las votaciones.

**Comment by CarlosGuerraLora** [comment]
Se procede a cerrar la rama ya que debido a algunos problemas para probar en remoto con Heroku ( como explica mi compañero [aquí](https://github.com/EGC-DECIDE-IO-Visualizacion/decide-io/issues/13#issuecomment-450389054) ) no se puede hacer.
