### ISSUE TITLE
Implementar los diferentes tipos de votaciones

### ISSUE THREAD

**Issue by javviram** [EGC-DECIDE-IO-Visualizacion/decide-io#7]
**¿Está tu petición de mejora relacionada con un problema? Por favor, describelo**
Se desea mostrar los distintos tipos de votaciones implementados por el módulo de voting.

**Describe la solución que te gustaría que se implementase**
Se debería coordinar el desarrollo con el módulo de Voting de tal modo que los tipos de votaciones desarrollados por ellos tengan una representación en el módulo de visualización.

**Comment by JesusPerezCarmona** [comment]
A la espera de que en el módulo Votación hagan avances en la creación de distintos tipos de votación, he hecho un código temporal que simularía la implementación de dichos tipos de votación en el 'visualizer'. Cuando los tipos de votación estén implementados, adaptaré mi código de modo que funcione con el trabajo realizado por el módulo de Votación.

**Comment by JesusPerezCarmona** [comment]
Se ha probado en local y no se producen errores, pero desgraciadamente, debido a que falta la implementación del trabajo del módulo de Votación, no se puede comprobar si mi código en su totalidad funciona correctamente. Se ha integrado la rama con la master y me dispongo a cerrar la incidencia.
